### ISSUE TITLE
Negative coordinates aren't preserved

### ISSUE THREAD

**Issue by dorobo-hamster** [dorobo-hamster/fcf-editor#5]
Files with negative coordinates can be loaded, but when modifying a label, the coordinates are converted into positive coordinates, and they are displayed as using the same coordinate system. Upon saving and loading, the chart shows the differences.

**Comment by gamecreater16** [comment]
That's a known issue, but the reason why I didn't fix it was because it's working fine with Kirikiri... The result is the same, whether the coordinates are positive or negative... Moreover, having positive coordinates to process is easier for the FCF editor, since it doesn't have to change the element's position, whereas it has to convert it to positive, along with adding margin when it's negative...

But, there's another issue with the current system: if you change few element's position to positive, and the others are still positive, then the position gets messed up totally... I think that's due to adding the margin and the least negative number to the already positive number for proper flow layout... Guess, the only option is to convert all the numbers to negative...

Also, this is just an opinion... You are free to change it however you wish!

**Comment by dorobo-hamster** [comment]
Fix bug: 57a1c39c3bd4974272b98c844c2400672caab96a
